export const ExtensionTypes = {
  POSITIONABLE: "positionable",
  COLLIDABLE: "collidable",
  CONSUMABLE: "consumable",
  DESTRUCTIBLE: "destructible",
  INTERACTIVE: "interactive",
  TRIGGERABLE: "triggerable",
  UPDATABLE: "updatable",
  TRIGGER_COOLDOWN_ATTACKER: "trigger-cooldown-attacker",
  EXPIRABLE: "expirable",
  INVENTORY: "inventory",
  IGNITABLE: "ignitable",
  MOVABLE: "movable",
  STATIC: "static",
  COMBUSTIBLE: "combustible",
  ILLUMINATED: "illuminated",
  CARRYABLE: "carryable",
  PLACEABLE: "placeable",
  GROUPABLE: "groupable",
  LANDMINE_UPDATE: "landmine-update",
  ONE_TIME_TRIGGER: "one-time-trigger",
  RESOURCES_BAG: "resources-bag",
  SNARED: "snared",
  POISON: "poison",
  ACID_TRIGGER: "acid-trigger",
  INFINITE_RUN: "infinite-run",
  TOXIC_GAS_CLOUD: "toxic-gas-cloud",
} as const;

export type ExtensionType = (typeof ExtensionTypes)[keyof typeof ExtensionTypes];
