import { ItemConfig } from "./item-registry";

export const ITEM_CONFIGS: Record<string, ItemConfig> = {
  bandage: {
    id: "bandage",
    category: "consumable",
    assets: {
      assetKey: "bandage",
      x: 48,
      y: 48,
      sheet: "items",
    },
    healable: true,
    spawn: {
      enabled: true,
      chance: 0.005,
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 10,
    },
    recipe: {
      enabled: true,
      components: [{ type: "cloth", count: 3 }],
    },
  },
  pain_pills: {
    id: "pain_pills",
    category: "consumable",
    assets: {
      assetKey: "pain_pills",
      x: 80,
      y: 48,
      sheet: "items",
    },
    healable: true,
    spawn: {
      enabled: true,
      chance: 0.006,
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 6,
    },
    recipe: {
      enabled: true,
      components: [{ type: "cloth", count: 1 }],
    },
  },
  pistol_ammo: {
    id: "pistol_ammo",
    category: "ammo",
    assets: {
      assetKey: "pistol_ammo",
      x: 64,
      y: 16,
      sheet: "items",
    },
    spawn: {
      enabled: true,
      chance: 0.005,
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 8,
      stackSize: 8,
    },
  },
  shotgun_ammo: {
    id: "shotgun_ammo",
    category: "ammo",
    assets: {
      assetKey: "shotgun_ammo",
      x: 80,
      y: 16,
      sheet: "items",
    },
    spawn: {
      enabled: true,
      chance: 0.005,
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 12,
      stackSize: 8,
    },
  },
  bolt_action_ammo: {
    id: "bolt_action_ammo",
    category: "ammo",
    assets: {
      assetKey: "bolt_action_ammo",
      x: 96,
      y: 16,
      sheet: "items",
    },
    spawn: {
      enabled: true,
      chance: 0.005,
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 15,
      stackSize: 10,
    },
  },
  ak47_ammo: {
    id: "ak47_ammo",
    category: "ammo",
    assets: {
      assetKey: "ak47_ammo",
      x: 112,
      y: 16,
      sheet: "items",
    },
    spawn: {
      enabled: true,
      chance: 0.005,
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 10,
      stackSize: 30,
    },
  },
  grenade_launcher_ammo: {
    id: "grenade_launcher_ammo",
    category: "ammo",
    assets: {
      assetKey: "grenade_launcher_ammo",
      x: 128,
      y: 16,
      sheet: "items",
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 25,
      stackSize: 4,
    },
  },
  flamethrower_ammo: {
    id: "flamethrower_ammo",
    category: "ammo",
    assets: {
      assetKey: "flamethrower_ammo",
      x: 144,
      y: 16,
      sheet: "items",
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 20,
      stackSize: 30,
    },
  },
  arrow_ammo: {
    id: "arrow_ammo",
    category: "ammo",
    assets: {
      assetKey: "arrow_ammo",
      x: 128,
      y: 32,
      sheet: "items",
    },
    spawn: {
      enabled: true,
      chance: 0.005,
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 8,
      stackSize: 16,
    },
  },
  landmine: {
    id: "landmine",
    category: "placeable",
    placeable: true,
    assets: {
      assetKey: "landmine",
      x: 16,
      y: 48,
      sheet: "items",
    },
    spawn: {
      enabled: true,
      chance: 0.001,
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 20,
    },
    autoPickup: false,
  },
  grenade: {
    id: "grenade",
    category: "throwable",
    assets: {
      assetKey: "grenade",
      x: 64,
      y: 0,
      sheet: "items",
    },
    spawn: {
      enabled: false,
      chance: 0,
    },
    merchant: {
      enabled: false,
      buyable: false,
      price: 20,
    },
  },
  torch: {
    id: "torch",
    category: "placeable",
    placeable: true,
    assets: {
      assetKey: "torch",
      x: 0,
      y: 0,
      sheet: "items",
    },
    spawn: {
      enabled: false,
      chance: 0, // do not spawn torches, players must craft them
    },
    fixtureRespawnMs: 180_000,
    merchant: {
      enabled: true,
      buyable: true,
      price: 5,
    },
    autoPickup: false,
    recipe: {
      enabled: true,
      components: [{ type: "wood" }, { type: "cloth" }],
    },
    lightIntensity: 300,
  },
  gasoline: {
    id: "gasoline",
    category: "placeable",
    placeable: true,
    assets: {
      assetKey: "gasoline",
      x: 0,
      y: 48,
      sheet: "items",
    },
    spawn: {
      enabled: true,
      chance: 0.002,
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 10,
    },
  },
  wood: {
    id: "wood",
    category: "ammo",
    assets: {
      assetKey: "wood",
      x: 64,
      y: 32,
      sheet: "items",
    },
    spawn: {
      enabled: true,
      chance: 0.1,
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 2,
    },
  },
  cloth: {
    id: "cloth",
    category: "ammo",
    assets: {
      assetKey: "cloth",
      x: 128,
      y: 0,
      sheet: "items",
    },
    spawn: {
      enabled: true,
      chance: 0.1,
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 4,
    },
  },
  coin: {
    id: "coin",
    category: "consumable",
    assets: {
      assetKey: "coin",
      x: 32,
      y: 48,
      sheet: "items",
    },
    autoPickup: true,
  },
  energy_drink: {
    id: "energy_drink",
    category: "consumable",
    assets: {
      assetKey: "energy_drink",
      x: 112,
      y: 144,
      sheet: "items",
    },
    spawn: {
      enabled: true,
      chance: 0.003,
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 15,
    },
    duration: 20, // Duration in seconds for unlimited running
  },
  crate: {
    id: "crate",
    category: "structure",
    assets: {
      assetKey: "crate",
      x: 0,
      y: 144,
      sheet: "items",
      totalFrames: 3,
    },
    autoPickup: true,
  },
  gallon_drum: {
    id: "gallon_drum",
    category: "structure",
    assets: {
      assetKey: "gallon_drum",
      x: 96,
      y: 144,
      sheet: "items",
    },
    spawn: {
      enabled: true,
      chance: 0.03,
    },
    autoPickup: true,
  },
  miners_hat: {
    id: "miners_hat",
    category: "armor",
    assets: {
      assetKey: "miners_hat",
      x: 48,
      y: 144,
      sheet: "items",
    },
    hideWhenSelected: true, // Don't show overlay when selected since player is wearing it
    wearable: true, // Armor: equips to head; body overlay when equipped (see player-body-overlays)
    equipmentSlot: "head",
    spawn: {
      enabled: true,
      chance: 0.0001,
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 30,
    },
    lightIntensity: 200,
  },
  spikes: {
    id: "spikes",
    category: "placeable",
    placeable: true,
    placeSound: "build",
    assets: {
      assetKey: "spikes",
      x: 0,
      y: 16,
      sheet: "items",
    },
    spawn: {
      enabled: true,
      chance: 0.003,
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 15,
    },
    recipe: {
      enabled: true,
      components: [{ type: "wood", count: 4 }],
    },
    upgradeTo: "spikes_level_2",
    autoPickup: false,
  },
  spikes_level_2: {
    id: "spikes_level_2",
    category: "placeable",
    placeable: true,
    placeSound: "build",
    assets: {
      assetKey: "spikes_level_2",
      x: 128,
      y: 128,
      sheet: "items",
    },
    spawn: {
      enabled: false,
      chance: 0,
    },
    merchant: {
      enabled: false,
      buyable: false,
      price: 0,
    },
    upgradeTo: "spikes_level_3",
    autoPickup: false,
  },
  spikes_level_3: {
    id: "spikes_level_3",
    category: "placeable",
    placeable: true,
    placeSound: "build",
    assets: {
      assetKey: "spikes_level_3",
      x: 128,
      y: 144,
      sheet: "items",
    },
    spawn: {
      enabled: false,
      chance: 0,
    },
    merchant: {
      enabled: false,
      buyable: false,
      price: 0,
    },
    autoPickup: false,
  },
  bear_trap: {
    id: "bear_trap",
    category: "structure",
    placeable: true,
    assets: {
      assetKey: "bear_trap",
      x: 64,
      y: 144,
      sheet: "items",
    },
    spawn: {
      enabled: true,
      chance: 0.002,
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 25,
    },
    recipe: {
      enabled: true,
      components: [
        { type: "wood", count: 3 },
        { type: "cloth", count: 1 },
      ],
    },
    autoPickup: false,
  },
  wall: {
    id: "wall",
    category: "structure",
    placeable: true,
    placeSound: "build",
    assets: {
      assetKey: "wall",
      x: 64,
      y: 48,
      sheet: "items",
    },
    spawn: {
      enabled: true,
      chance: 0.005,
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 8,
    },
    recipe: {
      enabled: true,
      components: [{ type: "wood", count: 2 }],
    },
    upgradeTo: "wall_level_2",
    autoPickup: false,
    isPassthrough: true,
  },
  wall_level_2: {
    id: "wall_level_2",
    category: "structure",
    placeable: true,
    placeSound: "build",
    assets: {
      assetKey: "wall_level_2",
      x: 144,
      y: 64,
      sheet: "items",
    },
    spawn: {
      enabled: false,
      chance: 0,
    },
    merchant: {
      enabled: false,
      buyable: false,
      price: 0,
    },
    upgradeTo: "wall_level_3",
    autoPickup: false,
    isPassthrough: true,
  },
  wall_level_3: {
    id: "wall_level_3",
    category: "structure",
    placeable: true,
    placeSound: "build",
    assets: {
      assetKey: "wall_level_3",
      x: 144,
      y: 80,
      sheet: "items",
    },
    spawn: {
      enabled: false,
      chance: 0,
    },
    merchant: {
      enabled: false,
      buyable: false,
      price: 0,
    },
    autoPickup: false,
    isPassthrough: true,
  },
  tree: {
    id: "tree",
    category: "structure",
    assets: {
      assetKey: "tree",
      x: 144,
      y: 0,
      sheet: "items",
    },
    spawn: {
      enabled: true,
      chance: 0.2,
    },
  },
  sentry_gun: {
    id: "sentry_gun",
    category: "structure",
    placeable: true,
    placeSound: "build",
    assets: {
      assetKey: "sentry_gun",
      x: 80,
      y: 144,
      sheet: "items",
    },
    merchant: {
      enabled: true,
      buyable: true,
      price: 100,
    },
    recipe: {
      enabled: true,
      components: [
        { type: "pistol" },
        { type: "pistol_ammo", count: 8 },
        { type: "wood", count: 3 },
        { type: "cloth", count: 2 },
      ],
    },
    upgradeTo: "sentry_gun_level_2",
    autoPickup: false,
    isPassthrough: true,
  },
  sentry_gun_level_2: {
    id: "sentry_gun_level_2",
    category: "structure",
    placeable: true,
    placeSound: "build",
    assets: {
      assetKey: "sentry_gun_level_2",
      x: 144,
      y: 128,
      sheet: "items",
    },
    spawn: {
      enabled: false,
      chance: 0,
    },
    merchant: {
      enabled: false,
      buyable: false,
      price: 0,
    },
    upgradeTo: "sentry_gun_level_3",
    autoPickup: false,
    isPassthrough: true,
  },
  sentry_gun_level_3: {
    id: "sentry_gun_level_3",
    category: "structure",
    placeable: true,
    placeSound: "build",
    assets: {
      assetKey: "sentry_gun_level_3",
      x: 144,
      y: 144,
      sheet: "items",
    },
    spawn: {
      enabled: false,
      chance: 0,
    },
    merchant: {
      enabled: false,
      buyable: false,
      price: 0,
    },
    autoPickup: false,
    isPassthrough: true,
  },
  forager_wraps: {
    id: "forager_wraps",
    category: "armor",
    assets: {
      assetKey: "forager_wraps",
      x: 64,
      y: 176,
      sheet: "items",
    },
    hideWhenSelected: true,
    wearable: true,
    rendersOnPlayerOverlay: false,
    equipmentSlot: "hands",
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  scout_pack: {
    id: "scout_pack",
    category: "armor",
    assets: {
      assetKey: "scout_pack",
      x: 80,
      y: 176,
      sheet: "items",
    },
    hideWhenSelected: true,
    wearable: true,
    rendersOnPlayerOverlay: false,
    equipmentSlot: "back",
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  tracker_boots: {
    id: "tracker_boots",
    category: "armor",
    assets: {
      assetKey: "tracker_boots",
      x: 96,
      y: 176,
      sheet: "items",
    },
    hideWhenSelected: true,
    wearable: true,
    rendersOnPlayerOverlay: false,
    equipmentSlot: "shoes",
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  dust_mask: {
    id: "dust_mask",
    category: "armor",
    assets: {
      assetKey: "dust_mask",
      x: 112,
      y: 176,
      sheet: "items",
    },
    hideWhenSelected: true,
    wearable: true,
    rendersOnPlayerOverlay: false,
    equipmentSlot: "head",
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  recon_poncho: {
    id: "recon_poncho",
    category: "armor",
    assets: {
      assetKey: "recon_poncho",
      x: 128,
      y: 176,
      sheet: "items",
    },
    hideWhenSelected: true,
    wearable: true,
    rendersOnPlayerOverlay: false,
    equipmentSlot: "shoulders",
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  survival_satchel: {
    id: "survival_satchel",
    category: "armor",
    assets: {
      assetKey: "survival_satchel",
      x: 144,
      y: 176,
      sheet: "items",
    },
    hideWhenSelected: true,
    wearable: true,
    rendersOnPlayerOverlay: false,
    equipmentSlot: "back",
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  reclaimed_plating: {
    id: "reclaimed_plating",
    category: "armor",
    assets: {
      assetKey: "reclaimed_plating",
      x: 0,
      y: 192,
      sheet: "items",
    },
    hideWhenSelected: true,
    wearable: true,
    rendersOnPlayerOverlay: false,
    equipmentSlot: "shoulders",
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  reclaimer_gloves: {
    id: "reclaimer_gloves",
    category: "armor",
    assets: {
      assetKey: "reclaimer_gloves",
      x: 16,
      y: 192,
      sheet: "items",
    },
    hideWhenSelected: true,
    wearable: true,
    rendersOnPlayerOverlay: false,
    equipmentSlot: "hands",
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  adrenal_tonic: {
    id: "adrenal_tonic",
    category: "consumable",
    assets: {
      assetKey: "adrenal_tonic",
      x: 32,
      y: 192,
      sheet: "items",
    },
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  combat_stim: {
    id: "combat_stim",
    category: "consumable",
    assets: {
      assetKey: "combat_stim",
      x: 48,
      y: 192,
      sheet: "items",
    },
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  cloth_hood: {
    id: "cloth_hood",
    category: "armor",
    assets: {
      assetKey: "cloth_hood",
      x: 64,
      y: 192,
      sheet: "items",
    },
    hideWhenSelected: true,
    wearable: true,
    rendersOnPlayerOverlay: false,
    equipmentSlot: "head",
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  patchwork_vest: {
    id: "patchwork_vest",
    category: "armor",
    assets: {
      assetKey: "patchwork_vest",
      x: 80,
      y: 192,
      sheet: "items",
    },
    hideWhenSelected: true,
    wearable: true,
    rendersOnPlayerOverlay: false,
    equipmentSlot: "torso",
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  stitched_pants: {
    id: "stitched_pants",
    category: "armor",
    assets: {
      assetKey: "stitched_pants",
      x: 96,
      y: 192,
      sheet: "items",
    },
    hideWhenSelected: true,
    wearable: true,
    rendersOnPlayerOverlay: false,
    equipmentSlot: "legs",
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  survivor_boots: {
    id: "survivor_boots",
    category: "armor",
    assets: {
      assetKey: "survivor_boots",
      x: 112,
      y: 192,
      sheet: "items",
    },
    hideWhenSelected: true,
    wearable: true,
    rendersOnPlayerOverlay: false,
    equipmentSlot: "shoes",
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  forager_cloak: {
    id: "forager_cloak",
    category: "armor",
    assets: {
      assetKey: "forager_cloak",
      x: 128,
      y: 192,
      sheet: "items",
    },
    hideWhenSelected: true,
    wearable: true,
    rendersOnPlayerOverlay: false,
    equipmentSlot: "shoulders",
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  reinforced_duster: {
    id: "reinforced_duster",
    category: "armor",
    assets: {
      assetKey: "reinforced_duster",
      x: 144,
      y: 192,
      sheet: "items",
    },
    hideWhenSelected: true,
    wearable: true,
    rendersOnPlayerOverlay: false,
    equipmentSlot: "torso",
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  trail_mix: {
    id: "trail_mix",
    category: "consumable",
    assets: {
      assetKey: "trail_mix",
      x: 0,
      y: 208,
      sheet: "items",
    },
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  stew_can: {
    id: "stew_can",
    category: "consumable",
    assets: {
      assetKey: "stew_can",
      x: 16,
      y: 208,
      sheet: "items",
    },
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  seasoned_rations: {
    id: "seasoned_rations",
    category: "consumable",
    assets: {
      assetKey: "seasoned_rations",
      x: 32,
      y: 208,
      sheet: "items",
    },
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  protein_plate: {
    id: "protein_plate",
    category: "consumable",
    assets: {
      assetKey: "protein_plate",
      x: 48,
      y: 208,
      sheet: "items",
    },
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  hearty_stew: {
    id: "hearty_stew",
    category: "consumable",
    assets: {
      assetKey: "hearty_stew",
      x: 64,
      y: 208,
      sheet: "items",
    },
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  campfire_feast: {
    id: "campfire_feast",
    category: "consumable",
    assets: {
      assetKey: "campfire_feast",
      x: 80,
      y: 208,
      sheet: "items",
    },
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
  },
  sign: {
    id: "sign",
    category: "structure",
    assets: {
      assetKey: "sign",
      x: 112,
      y: 208,
      sheet: "items",
    },
    spawn: {
      enabled: false,
      chance: 0,
    },
    merchant: {
      enabled: false,
      buyable: false,
      price: 0,
    },
    recipe: {
      enabled: true,
      components: [
        { type: "wood", count: 1 },
        { type: "paper", count: 1 },
      ],
      profession: "crafting",
      unlockLevel: 1,
      station: "workbench",
      professionXp: 6,
    },
    autoPickup: false,
  },
  skateboard: {
    id: "skateboard",
    category: "placeable",
    assets: {
      assetKey: "skateboard",
      x: 128,
      y: 208,
      sheet: "items",
    },
    spawn: { enabled: false, chance: 0 },
    merchant: { enabled: false, buyable: false, price: 0 },
    recipe: {
      enabled: true,
      components: [
        { type: "wood", count: 2 },
        { type: "cloth", count: 1 },
      ],
      profession: "crafting",
      unlockLevel: 1,
      station: "workbench",
      professionXp: 8,
    },
  },
};
