import { Entities, ZOMBIE_ATTACK_RADIUS } from "../constants";
import Vector2 from "../util/vector2";
import { ZombieConfig, EntityCategories } from "./zombie-registry";

export const ZOMBIE_CONFIGS: Record<string, ZombieConfig> = {
  [Entities.ZOMBIE]: {
    id: Entities.ZOMBIE,
    category: EntityCategories.ZOMBIE,
    stats: {
      speed: 35,
      health: 3,
      damage: 1,
      attackCooldown: 1,
      attackRadius: ZOMBIE_ATTACK_RADIUS,
      dropChance: 0.7,
      size: new Vector2(16, 16),
    },
    assets: {
      assetPrefix: "zombie",
      animationDuration: 500,
      debugWaypointColor: "yellow",
      minimapColor: "red",
      frameLayout: {
        startX: 496,
        downY: 76,
        leftY: 95,
        upY: 57,
        totalFrames: 3,
        sheet: "default", // Regular zombie uses default sheet
      },
      deadFrame: {
        x: 289,
        y: 19,
        sheet: "default", // Dead frame also on default sheet
      },
    },
    movementStrategy: "melee",
    attackStrategy: "melee",
  },
  [Entities.BIG_ZOMBIE]: {
    id: Entities.BIG_ZOMBIE,
    category: EntityCategories.ZOMBIE,
    stats: {
      speed: 20,
      health: 11,
      damage: 3,
      attackCooldown: 1.5,
      attackRadius: ZOMBIE_ATTACK_RADIUS,
      dropChance: 1,
      size: new Vector2(16, 16),
    },
    assets: {
      assetPrefix: "big_zombie",
      animationDuration: 500,
      debugWaypointColor: "orange",
      minimapColor: "red",
      frameLayout: {
        startX: 0,
        downY: 64,
        leftY: 80,
        upY: 48,
        totalFrames: 3,
        sheet: "characters",
      },
      deadFrame: {
        x: 144,
        y: 0,
        sheet: "characters",
      },
    },
    movementStrategy: "melee",
    attackStrategy: "melee",
  },
  [Entities.FAST_ZOMBIE]: {
    id: Entities.FAST_ZOMBIE,
    category: EntityCategories.ZOMBIE,
    stats: {
      speed: 45,
      health: 1,
      damage: 1,
      attackCooldown: 0.5,
      attackRadius: ZOMBIE_ATTACK_RADIUS,
      dropChance: 0.3,
      size: new Vector2(8, 8),
    },
    assets: {
      assetPrefix: "fast_zombie",
      animationDuration: 250,
      debugWaypointColor: "red",
      minimapColor: "red",
      frameLayout: {
        startX: 0,
        downY: 208,
        leftY: 224,
        upY: 192,
        totalFrames: 3,
        sheet: "characters",
      },
      deadFrame: {
        x: 144,
        y: 0,
        sheet: "characters",
      },
    },
    movementStrategy: "melee",
    attackStrategy: "melee",
  },
  [Entities.EXPLODING_ZOMBIE]: {
    id: Entities.EXPLODING_ZOMBIE,
    category: EntityCategories.ZOMBIE,
    stats: {
      speed: 45,
      health: 1,
      damage: 0, // Damage comes from explosion, not attack
      attackCooldown: 0.5,
      attackRadius: ZOMBIE_ATTACK_RADIUS,
      dropChance: 0.3,
      size: new Vector2(8, 8),
    },
    assets: {
      assetPrefix: "exploding_zombie",
      animationDuration: 250,
      debugWaypointColor: "red",
      minimapColor: "red",
      frameLayout: {
        startX: 0,
        downY: 64,
        leftY: 80,
        upY: 48,
        totalFrames: 3,
        sheet: "characters",
      },
      deadFrame: {
        x: 144,
        y: 0,
        sheet: "characters",
      },
    },
    movementStrategy: "melee",
    attackStrategy: "exploding",
  },
  [Entities.BAT_ZOMBIE]: {
    id: Entities.BAT_ZOMBIE,
    category: EntityCategories.ZOMBIE,
    stats: {
      speed: 30,
      health: 1,
      damage: 1,
      attackCooldown: 0.5,
      attackRadius: ZOMBIE_ATTACK_RADIUS,
      dropChance: 0.2,
      size: new Vector2(8, 8),
    },
    assets: {
      assetPrefix: "bat_zombie",
      animationDuration: 200,
      debugWaypointColor: "purple",
      minimapColor: "blue",
      frameLayout: {
        startX: 0,
        downY: 240,
        leftY: 240,
        upY: 240,
        totalFrames: 3,
        sheet: "characters",
      },
      deadFrame: {
        x: 48,
        y: 240,
        sheet: "characters",
      },
    },
    movementStrategy: "flying",
    attackStrategy: "melee",
  },
  [Entities.SPITTER_ZOMBIE]: {
    id: Entities.SPITTER_ZOMBIE,
    category: EntityCategories.ZOMBIE,
    stats: {
      speed: 25,
      health: 2,
      damage: 2,
      attackCooldown: 2,
      attackRadius: 100, // Larger attack radius for ranged
      dropChance: 0.5,
      size: new Vector2(16, 16),
    },
    assets: {
      assetPrefix: "spitter_zombie",
      animationDuration: 750,
      debugWaypointColor: "green",
      minimapColor: "purple",
      frameLayout: {
        startX: 0,
        downY: 160,
        leftY: 176,
        upY: 144,
        totalFrames: 4,
        sheet: "characters",
      },
      deadFrame: {
        x: 144,
        y: 0,
        sheet: "characters",
      },
    },
    movementStrategy: "ranged",
    attackStrategy: "ranged",
  },
};
