export const ServerSentEvents = {
  GAME_STATE_UPDATE: "gameStateUpdate",
  /** @deprecated Reserved for wire id stability; not used. */
  GAME_OVER: "gameOver",
  GAME_STARTED: "gameStarted",
  PLAYER_DEATH: "playerDeath",
  PLAYER_HURT: "playerHurt",
  PLAYER_LEFT: "playerLeft",
  PLAYER_JOINED: "playerJoined",
  YOUR_ID: "yourId",
  PLAYER_ATTACKED: "playerAttacked",
  PLAYER_DROPPED_ITEM: "playerDroppedItem",
  PLAYER_PICKED_UP_ITEM: "playerPickedUpItem",
  PLAYER_PICKED_UP_RESOURCE: "playerPickedUpResource",
  ZOMBIE_DEATH: "zombieDeath",
  ZOMBIE_HURT: "zombieHurt",
  ZOMBIE_ATTACKED: "zombieAttacked",
  ZOMBIE_ALERTED: "zombieAlerted",
  COIN_PICKUP: "coinPickup",
  BIG_ZOMBIE_DEATH: "bigZombieDeath",
  BIG_ZOMBIE_HURT: "bigZombieHurt",
  BIG_ZOMBIE_ATTACKED: "bigZombieAttacked",
  PICKUP_ITEM: "pickupItem",
  GUN_EMPTY: "gunEmpty",
  GUN_FIRED: "gunFired",
  LOOT: "loot",
  ENEMY_WAYPOINT: "enemyWaypoint",
  SERVER_UPDATING: "serverUpdating",
  PONG: "pong",
  CHAT_MESSAGE: "chatMessage",
  EXPLOSION: "explosion",
  GAME_MESSAGE: "gameMessage",
  CAR_REPAIR: "carRepair",
  CRAFT: "craft",
  BUILD: "build",
  BOSS_STEP: "bossStep",
  BOSS_SUMMON: "bossSummon",
  BOSS_SPLIT: "bossSplit",
  VERSION_MISMATCH: "versionMismatch",
  AUTH_REQUIRED: "authRequired",
  USER_BANNED: "userBanned",
  PROFILE_LOAD_FAILED: "profileLoadFailed",
  PLAYER_LEVEL_UP: "playerLevelUp",
} as const;

export const ClientSentEvents = {
  CRAFT_REQUEST: "craftRequest",
  PLAYER_INPUT: "playerInput",
  START_CRAFTING: "startCrafting",
  SET_DISPLAY_NAME: "setDisplayName",
  STOP_CRAFTING: "stopCrafting",
  REQUEST_FULL_STATE: "requestFullState",
  REQUEST_PLAYER_ID: "requestPlayerId",
  PING: "ping",
  PING_UPDATE: "pingUpdate",
  SEND_CHAT: "sendChat",
  MERCHANT_BUY: "merchantBuy",
  MERCHANT_SELL: "merchantSell",
  PLACE_STRUCTURE: "placeStructure",
  PLAYER_RESPAWN_REQUEST: "playerRespawnRequest",
  DROP_ITEM: "dropItem",
  CONSUME_ITEM: "consumeItem",
  SELECT_INVENTORY_SLOT: "selectInventorySlot",
  SWAP_INVENTORY_ITEMS: "swapInventoryItems",
  SWAP_BAG_AND_EQUIPMENT: "swapBagAndEquipment",
  INTERACT: "interact",
  CHANGE_PLAYER_COLOR: "changePlayerColor",
  SPAWN_ZOMBIE: "spawnZombie",
  SET_PROGRESSION_ALLOCATIONS: "setProgressionAllocations",
  SELECT_WEAPON_LOADOUT: "selectWeaponLoadout",
  SET_WEAPON_LOADOUT_SLOT: "setWeaponLoadoutSlot",
  DIALOGUE_NPC_COMPLETE: "dialogueNpcComplete",
  /** Consume from loadout consumable slot (key 4 / 5) without changing selected inventory or weapon row. */
  USE_LOADOUT_CONSUMABLE: "useLoadoutConsumable",
  /** Bank / locker: stash, withdraw, drop, use, equip (validated against locker proximity). */
  BANK_ACTION: "bankAction",
} as const;

export type ServerSentEventType = (typeof ServerSentEvents)[keyof typeof ServerSentEvents];
export type ClientSentEventType = (typeof ClientSentEvents)[keyof typeof ClientSentEvents];
export type EventType =
  | (typeof ServerSentEvents)[keyof typeof ServerSentEvents]
  | (typeof ClientSentEvents)[keyof typeof ClientSentEvents];
