export const TICK_RATE = 20;

// TODO: IF YOU SET THIS TOO LOW, THE GAME CRASHES BECAUSE ZOMBIES SPAWN BEFORE FULL INITIALIZATION
export const DAY_DURATION = 30;

export const NIGHT_DURATION = 60;

export const PERFORMANCE_LOG_INTERVAL = 5000;
export const TICK_RATE_MS = 1000 / TICK_RATE;
