/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorIndexRouteImport } from './routes/editor/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as PlayWorldWorldIdRouteImport } from './routes/play/world/$worldId'
import { Route as ApiSessionValidateRouteImport } from './routes/api/session/validate'
import { Route as ApiGameZombieKillRouteImport } from './routes/api/game/zombie-kill'
import { Route as ApiGameSkillAllocationsRouteImport } from './routes/api/game/skill-allocations'
import { Route as ApiGameProfessionProgressRouteImport } from './routes/api/game/profession-progress'
import { Route as ApiGamePlayerStatsRouteImport } from './routes/api/game/player-stats'
import { Route as ApiGamePlayerSessionRouteImport } from './routes/api/game/player-session'
import { Route as ApiGamePlayerRespawnBindRouteImport } from './routes/api/game/player-respawn-bind'
import { Route as ApiGamePlayerQuestProgressRouteImport } from './routes/api/game/player-quest-progress'
import { Route as ApiGamePlayerMapExplorationRouteImport } from './routes/api/game/player-map-exploration'
import { Route as ApiGamePlayerLastPositionRouteImport } from './routes/api/game/player-last-position'
import { Route as ApiGamePlayerExperienceRouteImport } from './routes/api/game/player-experience'
import { Route as ApiGameCharacterAllocationsRouteImport } from './routes/api/game/character-allocations'
import { Route as ApiGameAuctionHouseRouteImport } from './routes/api/game/auction-house'
import { Route as ApiGameAddExperienceRouteImport } from './routes/api/game/add-experience'
import { Route as ApiGameAbilityAllocationsRouteImport } from './routes/api/game/ability-allocations'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiGameServersIndexRouteImport } from './routes/api/game/servers/index'
import { Route as ApiGameServersRegisterRouteImport } from './routes/api/game/servers/register'
import { Route as ApiGameServersHeartbeatRouteImport } from './routes/api/game/servers/heartbeat'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayWorldWorldIdRoute = PlayWorldWorldIdRouteImport.update({
  id: '/world/$worldId',
  path: '/world/$worldId',
  getParentRoute: () => PlayRoute,
} as any)
const ApiSessionValidateRoute = ApiSessionValidateRouteImport.update({
  id: '/api/session/validate',
  path: '/api/session/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameZombieKillRoute = ApiGameZombieKillRouteImport.update({
  id: '/api/game/zombie-kill',
  path: '/api/game/zombie-kill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameSkillAllocationsRoute = ApiGameSkillAllocationsRouteImport.update({
  id: '/api/game/skill-allocations',
  path: '/api/game/skill-allocations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameProfessionProgressRoute =
  ApiGameProfessionProgressRouteImport.update({
    id: '/api/game/profession-progress',
    path: '/api/game/profession-progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGamePlayerStatsRoute = ApiGamePlayerStatsRouteImport.update({
  id: '/api/game/player-stats',
  path: '/api/game/player-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamePlayerSessionRoute = ApiGamePlayerSessionRouteImport.update({
  id: '/api/game/player-session',
  path: '/api/game/player-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamePlayerRespawnBindRoute =
  ApiGamePlayerRespawnBindRouteImport.update({
    id: '/api/game/player-respawn-bind',
    path: '/api/game/player-respawn-bind',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGamePlayerQuestProgressRoute =
  ApiGamePlayerQuestProgressRouteImport.update({
    id: '/api/game/player-quest-progress',
    path: '/api/game/player-quest-progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGamePlayerMapExplorationRoute =
  ApiGamePlayerMapExplorationRouteImport.update({
    id: '/api/game/player-map-exploration',
    path: '/api/game/player-map-exploration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGamePlayerLastPositionRoute =
  ApiGamePlayerLastPositionRouteImport.update({
    id: '/api/game/player-last-position',
    path: '/api/game/player-last-position',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGamePlayerExperienceRoute = ApiGamePlayerExperienceRouteImport.update({
  id: '/api/game/player-experience',
  path: '/api/game/player-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameCharacterAllocationsRoute =
  ApiGameCharacterAllocationsRouteImport.update({
    id: '/api/game/character-allocations',
    path: '/api/game/character-allocations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGameAuctionHouseRoute = ApiGameAuctionHouseRouteImport.update({
  id: '/api/game/auction-house',
  path: '/api/game/auction-house',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameAddExperienceRoute = ApiGameAddExperienceRouteImport.update({
  id: '/api/game/add-experience',
  path: '/api/game/add-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameAbilityAllocationsRoute =
  ApiGameAbilityAllocationsRouteImport.update({
    id: '/api/game/ability-allocations',
    path: '/api/game/ability-allocations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameServersIndexRoute = ApiGameServersIndexRouteImport.update({
  id: '/api/game/servers/',
  path: '/api/game/servers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameServersRegisterRoute = ApiGameServersRegisterRouteImport.update({
  id: '/api/game/servers/register',
  path: '/api/game/servers/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameServersHeartbeatRoute = ApiGameServersHeartbeatRouteImport.update({
  id: '/api/game/servers/heartbeat',
  path: '/api/game/servers/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/editor': typeof EditorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/game/ability-allocations': typeof ApiGameAbilityAllocationsRoute
  '/api/game/add-experience': typeof ApiGameAddExperienceRoute
  '/api/game/auction-house': typeof ApiGameAuctionHouseRoute
  '/api/game/character-allocations': typeof ApiGameCharacterAllocationsRoute
  '/api/game/player-experience': typeof ApiGamePlayerExperienceRoute
  '/api/game/player-last-position': typeof ApiGamePlayerLastPositionRoute
  '/api/game/player-map-exploration': typeof ApiGamePlayerMapExplorationRoute
  '/api/game/player-quest-progress': typeof ApiGamePlayerQuestProgressRoute
  '/api/game/player-respawn-bind': typeof ApiGamePlayerRespawnBindRoute
  '/api/game/player-session': typeof ApiGamePlayerSessionRoute
  '/api/game/player-stats': typeof ApiGamePlayerStatsRoute
  '/api/game/profession-progress': typeof ApiGameProfessionProgressRoute
  '/api/game/skill-allocations': typeof ApiGameSkillAllocationsRoute
  '/api/game/zombie-kill': typeof ApiGameZombieKillRoute
  '/api/session/validate': typeof ApiSessionValidateRoute
  '/play/world/$worldId': typeof PlayWorldWorldIdRoute
  '/api/game/servers/heartbeat': typeof ApiGameServersHeartbeatRoute
  '/api/game/servers/register': typeof ApiGameServersRegisterRoute
  '/api/game/servers': typeof ApiGameServersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/editor': typeof EditorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/game/ability-allocations': typeof ApiGameAbilityAllocationsRoute
  '/api/game/add-experience': typeof ApiGameAddExperienceRoute
  '/api/game/auction-house': typeof ApiGameAuctionHouseRoute
  '/api/game/character-allocations': typeof ApiGameCharacterAllocationsRoute
  '/api/game/player-experience': typeof ApiGamePlayerExperienceRoute
  '/api/game/player-last-position': typeof ApiGamePlayerLastPositionRoute
  '/api/game/player-map-exploration': typeof ApiGamePlayerMapExplorationRoute
  '/api/game/player-quest-progress': typeof ApiGamePlayerQuestProgressRoute
  '/api/game/player-respawn-bind': typeof ApiGamePlayerRespawnBindRoute
  '/api/game/player-session': typeof ApiGamePlayerSessionRoute
  '/api/game/player-stats': typeof ApiGamePlayerStatsRoute
  '/api/game/profession-progress': typeof ApiGameProfessionProgressRoute
  '/api/game/skill-allocations': typeof ApiGameSkillAllocationsRoute
  '/api/game/zombie-kill': typeof ApiGameZombieKillRoute
  '/api/session/validate': typeof ApiSessionValidateRoute
  '/play/world/$worldId': typeof PlayWorldWorldIdRoute
  '/api/game/servers/heartbeat': typeof ApiGameServersHeartbeatRoute
  '/api/game/servers/register': typeof ApiGameServersRegisterRoute
  '/api/game/servers': typeof ApiGameServersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/editor/': typeof EditorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/game/ability-allocations': typeof ApiGameAbilityAllocationsRoute
  '/api/game/add-experience': typeof ApiGameAddExperienceRoute
  '/api/game/auction-house': typeof ApiGameAuctionHouseRoute
  '/api/game/character-allocations': typeof ApiGameCharacterAllocationsRoute
  '/api/game/player-experience': typeof ApiGamePlayerExperienceRoute
  '/api/game/player-last-position': typeof ApiGamePlayerLastPositionRoute
  '/api/game/player-map-exploration': typeof ApiGamePlayerMapExplorationRoute
  '/api/game/player-quest-progress': typeof ApiGamePlayerQuestProgressRoute
  '/api/game/player-respawn-bind': typeof ApiGamePlayerRespawnBindRoute
  '/api/game/player-session': typeof ApiGamePlayerSessionRoute
  '/api/game/player-stats': typeof ApiGamePlayerStatsRoute
  '/api/game/profession-progress': typeof ApiGameProfessionProgressRoute
  '/api/game/skill-allocations': typeof ApiGameSkillAllocationsRoute
  '/api/game/zombie-kill': typeof ApiGameZombieKillRoute
  '/api/session/validate': typeof ApiSessionValidateRoute
  '/play/world/$worldId': typeof PlayWorldWorldIdRoute
  '/api/game/servers/heartbeat': typeof ApiGameServersHeartbeatRoute
  '/api/game/servers/register': typeof ApiGameServersRegisterRoute
  '/api/game/servers/': typeof ApiGameServersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/play'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/api/health'
    | '/editor'
    | '/api/auth/$'
    | '/api/game/ability-allocations'
    | '/api/game/add-experience'
    | '/api/game/auction-house'
    | '/api/game/character-allocations'
    | '/api/game/player-experience'
    | '/api/game/player-last-position'
    | '/api/game/player-map-exploration'
    | '/api/game/player-quest-progress'
    | '/api/game/player-respawn-bind'
    | '/api/game/player-session'
    | '/api/game/player-stats'
    | '/api/game/profession-progress'
    | '/api/game/skill-allocations'
    | '/api/game/zombie-kill'
    | '/api/session/validate'
    | '/play/world/$worldId'
    | '/api/game/servers/heartbeat'
    | '/api/game/servers/register'
    | '/api/game/servers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/play'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/api/health'
    | '/editor'
    | '/api/auth/$'
    | '/api/game/ability-allocations'
    | '/api/game/add-experience'
    | '/api/game/auction-house'
    | '/api/game/character-allocations'
    | '/api/game/player-experience'
    | '/api/game/player-last-position'
    | '/api/game/player-map-exploration'
    | '/api/game/player-quest-progress'
    | '/api/game/player-respawn-bind'
    | '/api/game/player-session'
    | '/api/game/player-stats'
    | '/api/game/profession-progress'
    | '/api/game/skill-allocations'
    | '/api/game/zombie-kill'
    | '/api/session/validate'
    | '/play/world/$worldId'
    | '/api/game/servers/heartbeat'
    | '/api/game/servers/register'
    | '/api/game/servers'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/play'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/api/health'
    | '/editor/'
    | '/api/auth/$'
    | '/api/game/ability-allocations'
    | '/api/game/add-experience'
    | '/api/game/auction-house'
    | '/api/game/character-allocations'
    | '/api/game/player-experience'
    | '/api/game/player-last-position'
    | '/api/game/player-map-exploration'
    | '/api/game/player-quest-progress'
    | '/api/game/player-respawn-bind'
    | '/api/game/player-session'
    | '/api/game/player-stats'
    | '/api/game/profession-progress'
    | '/api/game/skill-allocations'
    | '/api/game/zombie-kill'
    | '/api/session/validate'
    | '/play/world/$worldId'
    | '/api/game/servers/heartbeat'
    | '/api/game/servers/register'
    | '/api/game/servers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PlayRoute: typeof PlayRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermsRoute: typeof TermsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  EditorIndexRoute: typeof EditorIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGameAbilityAllocationsRoute: typeof ApiGameAbilityAllocationsRoute
  ApiGameAddExperienceRoute: typeof ApiGameAddExperienceRoute
  ApiGameAuctionHouseRoute: typeof ApiGameAuctionHouseRoute
  ApiGameCharacterAllocationsRoute: typeof ApiGameCharacterAllocationsRoute
  ApiGamePlayerExperienceRoute: typeof ApiGamePlayerExperienceRoute
  ApiGamePlayerLastPositionRoute: typeof ApiGamePlayerLastPositionRoute
  ApiGamePlayerMapExplorationRoute: typeof ApiGamePlayerMapExplorationRoute
  ApiGamePlayerQuestProgressRoute: typeof ApiGamePlayerQuestProgressRoute
  ApiGamePlayerRespawnBindRoute: typeof ApiGamePlayerRespawnBindRoute
  ApiGamePlayerSessionRoute: typeof ApiGamePlayerSessionRoute
  ApiGamePlayerStatsRoute: typeof ApiGamePlayerStatsRoute
  ApiGameProfessionProgressRoute: typeof ApiGameProfessionProgressRoute
  ApiGameSkillAllocationsRoute: typeof ApiGameSkillAllocationsRoute
  ApiGameZombieKillRoute: typeof ApiGameZombieKillRoute
  ApiSessionValidateRoute: typeof ApiSessionValidateRoute
  ApiGameServersHeartbeatRoute: typeof ApiGameServersHeartbeatRoute
  ApiGameServersRegisterRoute: typeof ApiGameServersRegisterRoute
  ApiGameServersIndexRoute: typeof ApiGameServersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/world/$worldId': {
      id: '/play/world/$worldId'
      path: '/world/$worldId'
      fullPath: '/play/world/$worldId'
      preLoaderRoute: typeof PlayWorldWorldIdRouteImport
      parentRoute: typeof PlayRoute
    }
    '/api/session/validate': {
      id: '/api/session/validate'
      path: '/api/session/validate'
      fullPath: '/api/session/validate'
      preLoaderRoute: typeof ApiSessionValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/zombie-kill': {
      id: '/api/game/zombie-kill'
      path: '/api/game/zombie-kill'
      fullPath: '/api/game/zombie-kill'
      preLoaderRoute: typeof ApiGameZombieKillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/skill-allocations': {
      id: '/api/game/skill-allocations'
      path: '/api/game/skill-allocations'
      fullPath: '/api/game/skill-allocations'
      preLoaderRoute: typeof ApiGameSkillAllocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/profession-progress': {
      id: '/api/game/profession-progress'
      path: '/api/game/profession-progress'
      fullPath: '/api/game/profession-progress'
      preLoaderRoute: typeof ApiGameProfessionProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/player-stats': {
      id: '/api/game/player-stats'
      path: '/api/game/player-stats'
      fullPath: '/api/game/player-stats'
      preLoaderRoute: typeof ApiGamePlayerStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/player-session': {
      id: '/api/game/player-session'
      path: '/api/game/player-session'
      fullPath: '/api/game/player-session'
      preLoaderRoute: typeof ApiGamePlayerSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/player-respawn-bind': {
      id: '/api/game/player-respawn-bind'
      path: '/api/game/player-respawn-bind'
      fullPath: '/api/game/player-respawn-bind'
      preLoaderRoute: typeof ApiGamePlayerRespawnBindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/player-quest-progress': {
      id: '/api/game/player-quest-progress'
      path: '/api/game/player-quest-progress'
      fullPath: '/api/game/player-quest-progress'
      preLoaderRoute: typeof ApiGamePlayerQuestProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/player-map-exploration': {
      id: '/api/game/player-map-exploration'
      path: '/api/game/player-map-exploration'
      fullPath: '/api/game/player-map-exploration'
      preLoaderRoute: typeof ApiGamePlayerMapExplorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/player-last-position': {
      id: '/api/game/player-last-position'
      path: '/api/game/player-last-position'
      fullPath: '/api/game/player-last-position'
      preLoaderRoute: typeof ApiGamePlayerLastPositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/player-experience': {
      id: '/api/game/player-experience'
      path: '/api/game/player-experience'
      fullPath: '/api/game/player-experience'
      preLoaderRoute: typeof ApiGamePlayerExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/character-allocations': {
      id: '/api/game/character-allocations'
      path: '/api/game/character-allocations'
      fullPath: '/api/game/character-allocations'
      preLoaderRoute: typeof ApiGameCharacterAllocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/auction-house': {
      id: '/api/game/auction-house'
      path: '/api/game/auction-house'
      fullPath: '/api/game/auction-house'
      preLoaderRoute: typeof ApiGameAuctionHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/add-experience': {
      id: '/api/game/add-experience'
      path: '/api/game/add-experience'
      fullPath: '/api/game/add-experience'
      preLoaderRoute: typeof ApiGameAddExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/ability-allocations': {
      id: '/api/game/ability-allocations'
      path: '/api/game/ability-allocations'
      fullPath: '/api/game/ability-allocations'
      preLoaderRoute: typeof ApiGameAbilityAllocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/servers/': {
      id: '/api/game/servers/'
      path: '/api/game/servers'
      fullPath: '/api/game/servers'
      preLoaderRoute: typeof ApiGameServersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/servers/register': {
      id: '/api/game/servers/register'
      path: '/api/game/servers/register'
      fullPath: '/api/game/servers/register'
      preLoaderRoute: typeof ApiGameServersRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/servers/heartbeat': {
      id: '/api/game/servers/heartbeat'
      path: '/api/game/servers/heartbeat'
      fullPath: '/api/game/servers/heartbeat'
      preLoaderRoute: typeof ApiGameServersHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlayRouteChildren {
  PlayWorldWorldIdRoute: typeof PlayWorldWorldIdRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayWorldWorldIdRoute: PlayWorldWorldIdRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  PlayRoute: PlayRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermsRoute: TermsRoute,
  ApiHealthRoute: ApiHealthRoute,
  EditorIndexRoute: EditorIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGameAbilityAllocationsRoute: ApiGameAbilityAllocationsRoute,
  ApiGameAddExperienceRoute: ApiGameAddExperienceRoute,
  ApiGameAuctionHouseRoute: ApiGameAuctionHouseRoute,
  ApiGameCharacterAllocationsRoute: ApiGameCharacterAllocationsRoute,
  ApiGamePlayerExperienceRoute: ApiGamePlayerExperienceRoute,
  ApiGamePlayerLastPositionRoute: ApiGamePlayerLastPositionRoute,
  ApiGamePlayerMapExplorationRoute: ApiGamePlayerMapExplorationRoute,
  ApiGamePlayerQuestProgressRoute: ApiGamePlayerQuestProgressRoute,
  ApiGamePlayerRespawnBindRoute: ApiGamePlayerRespawnBindRoute,
  ApiGamePlayerSessionRoute: ApiGamePlayerSessionRoute,
  ApiGamePlayerStatsRoute: ApiGamePlayerStatsRoute,
  ApiGameProfessionProgressRoute: ApiGameProfessionProgressRoute,
  ApiGameSkillAllocationsRoute: ApiGameSkillAllocationsRoute,
  ApiGameZombieKillRoute: ApiGameZombieKillRoute,
  ApiSessionValidateRoute: ApiSessionValidateRoute,
  ApiGameServersHeartbeatRoute: ApiGameServersHeartbeatRoute,
  ApiGameServersRegisterRoute: ApiGameServersRegisterRoute,
  ApiGameServersIndexRoute: ApiGameServersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
