export { AIPlayerManager } from "./ai-player-manager";
export { AIController } from "./ai-controller";
export { AIStateMachine, AIState, KitePhase } from "./ai-state-machine";
export type { ThreatInfo } from "./ai-state-machine";
export { AITargetingSystem } from "./ai-targeting";
export type { AITarget } from "./ai-targeting";
export { AIPathfinder } from "./ai-pathfinding";
export { generateHumanName, resetUsedNames } from "./ai-names";
export { AI_CONFIG, GOOD_WEAPONS, ALL_WEAPONS, WEAPON_AMMO_MAP, WEAPON_RANGES, WEAPON_PRIORITY, MELEE_WEAPONS } from "./ai-config";
export type { AIStateHandler, AIStateContext } from "./states/base-state";
export { AIInteractionHelper } from "./ai-interaction-helper";
export type { InteractionResult } from "./ai-interaction-helper";
